# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MOELoader
                                 A QGIS plugin
 環境省が提供する地理空間情報ポータルサイト「環境ジオポータル」のデータを、QGISに直接読み込むためのプラグインです。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-01
        copyright            : (C) 2025 by Keita Uemori
        email                : geo.jagaimo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Keita Uemori'
__date__ = '2025-10-01'
__copyright__ = '(C) 2025 by Keita Uemori'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MOELoader class from file MOELoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .moe_geoportal_loader import MOEGeoportalLoader
    return MOEGeoportalLoader()
